# 기본 디렉터리 설정
music_directory    "/music"
playlist_directory "/var/lib/mpd/playlists"
db_file            "/var/lib/mpd/database"
state_file         "/var/lib/mpd/state"
sticker_file       "/var/lib/mpd/sticker.sql"
log_file           "/dev/stdout"
pid_file           "/var/run/mpd/mpd.pid"

# 네트워크 설정
bind_to_address    "0.0.0.0"
port               "6600"
default_permissions "read,add,control,admin"

audio_output {
    type            "pipewire"
    name            "PipeWire Output"
}

audio_output {
    type            "httpd"
    name            "MPD Opus Stream"
    encoder         "opus"
    port            "8800"
    bind_to_address "0.0.0.0"
    always_on       "yes"
    tags            "yes"
    max_clients     "3"
    bitrate         "128000"        
    format          "48000:16:2"
}
